"""add effort column to llm_runs

Revision ID: 16b3688378b5
Revises: 47bc83859243
Create Date: 2026-05-22 02:55:05.768060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b3688378b5'
down_revision: Union[str, Sequence[str], None] = '47bc83859243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effort', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.drop_column('effort')

    # ### end Alembic commands ###
