"""add candidate_signals.created_at

Revision ID: 47bc83859243
Revises: cda196c18c5a
Create Date: 2026-05-21 19:49:54.656554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47bc83859243'
down_revision: Union[str, Sequence[str], None] = 'cda196c18c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default lets existing rows inherit a timestamp at migration time;
    # application code overwrites with _utcnow on insert per the model default.
    with op.batch_alter_table('candidate_signals', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created_at',
                sa.DateTime(timezone=True),
                server_default=sa.text('CURRENT_TIMESTAMP'),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_signals', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
