"""telemetry tables: llm_runs scheduler_runs api_usage

Revision ID: 5c50e53c0454
Revises: c90f4f1a33eb
Create Date: 2026-05-18 00:29:26.577024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c50e53c0454'
down_revision: Union[str, Sequence[str], None] = 'c90f4f1a33eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'day', name='uq_api_usage_provider_day')
    )
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_provider'), ['provider'], unique=False)

    op.create_table('scheduler_runs',
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduler_runs', schema=None) as batch_op:
        batch_op.create_index('ix_scheduler_runs_job_id_started_at', ['job_id', 'started_at'], unique=False)

    op.create_table('llm_runs',
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_runs_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_runs_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_runs_task'), ['task'], unique=False)
        batch_op.create_index('ix_llm_runs_task_created_at', ['task', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_runs_task_created_at')
        batch_op.drop_index(batch_op.f('ix_llm_runs_task'))
        batch_op.drop_index(batch_op.f('ix_llm_runs_model'))
        batch_op.drop_index(batch_op.f('ix_llm_runs_candidate_id'))

    op.drop_table('llm_runs')
    with op.batch_alter_table('scheduler_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_scheduler_runs_job_id_started_at')

    op.drop_table('scheduler_runs')
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_provider'))

    op.drop_table('api_usage')
    # ### end Alembic commands ###
