"""initial schema: sources raw_signals candidates

Revision ID: 879075ae2c6e
Revises: 
Create Date: 2026-05-18 00:17:58.337214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879075ae2c6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('suspected_user', sa.Text(), nullable=True),
    sa.Column('seed_keywords_json', sa.JSON(), nullable=False),
    sa.Column('vertical', sa.String(length=100), nullable=True),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.Enum('pending', 'approved', 'rejected', 'auto_killed', name='decision', native_enum=False, length=20), nullable=False),
    sa.Column('pipeline_stage', sa.Enum('none', 'competitive', 'scoring', 'synthesizing', 'done', 'failed', name='pipelinestage', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('pending', 'approved', 'rejected', 'auto_killed')", name='ck_candidates_decision'),
    sa.CheckConstraint("pipeline_stage IN ('none', 'competitive', 'scoring', 'synthesizing', 'done', 'failed')", name='ck_candidates_pipeline_stage'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_pipeline_stage'), ['pipeline_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_vertical'), ['vertical'], unique=False)

    op.create_table('sources',
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_kind'), ['kind'], unique=False)

    op.create_table('raw_signals',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vertical', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    with op.batch_alter_table('raw_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_signals_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_signals_vertical'), ['vertical'], unique=False)

    op.create_table('candidate_signals',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('raw_signal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_signal_id'], ['raw_signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id', 'raw_signal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_signals')
    with op.batch_alter_table('raw_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_signals_vertical'))
        batch_op.drop_index(batch_op.f('ix_raw_signals_source_id'))

    op.drop_table('raw_signals')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_kind'))

    op.drop_table('sources')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_vertical'))
        batch_op.drop_index(batch_op.f('ix_candidates_pipeline_stage'))
        batch_op.drop_index(batch_op.f('ix_candidates_decision'))

    op.drop_table('candidates')
    # ### end Alembic commands ###
