"""add retry_log_json column to llm_runs

Revision ID: c448292f13fe
Revises: c9654c48dc33
Create Date: 2026-05-18 02:55:27.975407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c448292f13fe'
down_revision: Union[str, Sequence[str], None] = 'c9654c48dc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_log_json', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.drop_column('retry_log_json')

    # ### end Alembic commands ###
