"""core pipeline tables and candidate_signals reverse index

Revision ID: c90f4f1a33eb
Revises: 879075ae2c6e
Create Date: 2026-05-18 00:27:45.311727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90f4f1a33eb'
down_revision: Union[str, Sequence[str], None] = '879075ae2c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'reject', name='approvaldecision', native_enum=False, length=10), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('approve', 'reject')", name='ck_approvals_decision'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('competitive_analyses',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('competitor_name', sa.String(length=255), nullable=False),
    sa.Column('competitor_url', sa.Text(), nullable=True),
    sa.Column('pricing_json', sa.JSON(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('funding_json', sa.JSON(), nullable=False),
    sa.Column('reviews_summary_json', sa.JSON(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitive_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitive_analyses_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('demand_checks',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trend_slope', sa.Float(), nullable=True),
    sa.Column('autosuggest_json', sa.JSON(), nullable=False),
    sa.Column('verdict', sa.Enum('pass', 'fail', name='demandverdict', native_enum=False, length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verdict IN ('pass', 'fail')", name='ck_demand_checks_verdict'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demand_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_checks_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_checks_verdict'), ['verdict'], unique=False)

    op.create_table('opportunities',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('top_complaints_json', sa.JSON(), nullable=False),
    sa.Column('feature_gaps_json', sa.JSON(), nullable=False),
    sa.Column('pricing_gaps_json', sa.JSON(), nullable=False),
    sa.Column('vertical_wedge', sa.Text(), nullable=True),
    sa.Column('sources_json', sa.JSON(), nullable=False),
    sa.Column('synthesized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', 'built', name='opportunitystatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived', 'built')", name='ck_opportunities_status'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_status'), ['status'], unique=False)

    op.create_table('scores',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('demand', sa.Float(), nullable=False),
    sa.Column('supply', sa.Float(), nullable=False),
    sa.Column('unmet_pain', sa.Float(), nullable=False),
    sa.Column('moat_potential', sa.Float(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('breakdown_json', sa.JSON(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_composite'), ['composite'], unique=False)

    op.create_table('projects',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('subdomain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('placeholder', 'in_dev', 'live', 'sunset', name='projectstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('placeholder', 'in_dev', 'live', 'sunset')", name='ck_projects_status'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    with op.batch_alter_table('candidate_signals', schema=None) as batch_op:
        batch_op.create_index('ix_candidate_signals_raw_signal_id', ['raw_signal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_signals', schema=None) as batch_op:
        batch_op.drop_index('ix_candidate_signals_raw_signal_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_opportunity_id'))

    op.drop_table('projects')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_composite'))
        batch_op.drop_index(batch_op.f('ix_scores_candidate_id'))

    op.drop_table('scores')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_status'))

    op.drop_table('opportunities')
    with op.batch_alter_table('demand_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_checks_verdict'))
        batch_op.drop_index(batch_op.f('ix_demand_checks_candidate_id'))

    op.drop_table('demand_checks')
    with op.batch_alter_table('competitive_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitive_analyses_candidate_id'))

    op.drop_table('competitive_analyses')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_candidate_id'))

    op.drop_table('approvals')
    # ### end Alembic commands ###
