"""add attempts column to llm_runs

Revision ID: c9654c48dc33
Revises: 5c50e53c0454
Create Date: 2026-05-18 00:53:22.024686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9654c48dc33'
down_revision: Union[str, Sequence[str], None] = '5c50e53c0454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.drop_column('attempts')

    # ### end Alembic commands ###
