"""add signal_text table

Revision ID: cda196c18c5a
Revises: cf695f497312
Create Date: 2026-05-21 15:39:08.023857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda196c18c5a'
down_revision: Union[str, Sequence[str], None] = 'cf695f497312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_text',
    sa.Column('raw_signal_id', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('social_proof_weight', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('is_low_signal', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['raw_signal_id'], ['raw_signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_text', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_text_raw_signal_id'), ['raw_signal_id'], unique=True)
        batch_op.create_index('ix_signal_text_source_kind', ['source_kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal_text', schema=None) as batch_op:
        batch_op.drop_index('ix_signal_text_source_kind')
        batch_op.drop_index(batch_op.f('ix_signal_text_raw_signal_id'))

    op.drop_table('signal_text')
    # ### end Alembic commands ###
