"""add consecutive_failures column to sources

Revision ID: cf695f497312
Revises: c448292f13fe
Create Date: 2026-05-19 01:23:01.074774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf695f497312'
down_revision: Union[str, Sequence[str], None] = 'c448292f13fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_column('consecutive_failures')

    # ### end Alembic commands ###
